pkg/controller/ttl_manager: Do not block on deleting pods in digestPods
openshift/ci-ns-ttl-controller pull request #7
Opened 2020-10-07 18:49 UTC by wking

@alvaroaleman [pointed out][1] that pods could have finalizers and similar that keep them from completely deleting.  But as far as "are we ready to remove this namespace?" is concerned, the fact that a pod is working trough the deletion process is enough for it to make it non-blocking.

[1]: https://github.com/openshift/ci-tools/pull/1277#discussion_r501066404

2020-10-07 19:02 UTC, alvaroaleman requested changes
tests?

2020-10-08 19:40 UTC, wking commented
> tests?

Unit tests good enough?  I don't see an e2e presubmit...

2020-10-08 19:56 UTC, alvaroaleman commented
> Unit tests good enough? I don't see an e2e presubmit...

Yeah, unit tests are good enough

2020-10-09 23:11 UTC, wking commented
Added a unit test with d826922 -> 5c61c33.

2020-10-21 11:22 UTC, petr-muller approved these changes

2020-10-21 11:59 UTC, merged